version: "3"

dotenv: ['.env']

tasks:
  build:
    cmds:
      - go build -o app cmd/server/main.go

  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run

  run:
    cmds:
      - docker-compose up --build

  dev:
    cmds:
      - export SENDGRID_API_KEY="$SENDGRID_API_KEY" && export CLIENT_API_KEY="$CLIENT_API_KEY" && reflex -s go run cmd/server/main.go
